# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_semiautomaticclassificationplugin_dock_class.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockClass(object):
    def setupUi(self, DockClass):
        DockClass.setObjectName("DockClass")
        DockClass.resize(426, 585)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DockClass.sizePolicy().hasHeightForWidth())
        DockClass.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.SCP_toolBox = QtWidgets.QToolBox(self.dockWidgetContents)
        self.SCP_toolBox.setObjectName("SCP_toolBox")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 408, 492))
        self.page_5.setObjectName("page_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.page_5)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.bandcalc_toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.bandcalc_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_bandcalc_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bandcalc_toolButton_2.setIcon(icon)
        self.bandcalc_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.bandcalc_toolButton_2.setObjectName("bandcalc_toolButton_2")
        self.gridLayout_40.addWidget(self.bandcalc_toolButton_2, 0, 5, 1, 1)
        self.ROItools_toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.ROItools_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_roi_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ROItools_toolButton_2.setIcon(icon1)
        self.ROItools_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.ROItools_toolButton_2.setObjectName("ROItools_toolButton_2")
        self.gridLayout_40.addWidget(self.ROItools_toolButton_2, 0, 2, 1, 1)
        self.preprocessing_toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.preprocessing_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_class_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preprocessing_toolButton_2.setIcon(icon2)
        self.preprocessing_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.preprocessing_toolButton_2.setObjectName("preprocessing_toolButton_2")
        self.gridLayout_40.addWidget(self.preprocessing_toolButton_2, 0, 3, 1, 1)
        self.settings_toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.settings_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_settings_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_toolButton_2.setIcon(icon3)
        self.settings_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.settings_toolButton_2.setObjectName("settings_toolButton_2")
        self.gridLayout_40.addWidget(self.settings_toolButton_2, 0, 7, 1, 1)
        self.postprocessing_toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.postprocessing_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_post_process.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.postprocessing_toolButton_2.setIcon(icon4)
        self.postprocessing_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.postprocessing_toolButton_2.setObjectName("postprocessing_toolButton_2")
        self.gridLayout_40.addWidget(self.postprocessing_toolButton_2, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_40.addItem(spacerItem, 0, 10, 1, 1)
        self.userguide_toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.userguide_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/guide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userguide_toolButton_2.setIcon(icon5)
        self.userguide_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.userguide_toolButton_2.setObjectName("userguide_toolButton_2")
        self.gridLayout_40.addWidget(self.userguide_toolButton_2, 0, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_40.addItem(spacerItem1, 0, 0, 1, 1)
        self.help_toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.help_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_toolButton_2.setIcon(icon6)
        self.help_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.help_toolButton_2.setObjectName("help_toolButton_2")
        self.gridLayout_40.addWidget(self.help_toolButton_2, 0, 9, 1, 1)
        self.download_images_toolButton_2 = QtWidgets.QToolButton(self.frame_3)
        self.download_images_toolButton_2.setStyleSheet("margin: 0px;padding: 0px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_download_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_images_toolButton_2.setIcon(icon7)
        self.download_images_toolButton_2.setIconSize(QtCore.QSize(22, 22))
        self.download_images_toolButton_2.setObjectName("download_images_toolButton_2")
        self.gridLayout_40.addWidget(self.download_images_toolButton_2, 0, 1, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_40, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_36, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_33.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_33.setObjectName("label_33")
        self.gridLayout_18.addWidget(self.label_33, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.trainingFile_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.trainingFile_lineEdit.setEnabled(False)
        self.trainingFile_lineEdit.setObjectName("trainingFile_lineEdit")
        self.gridLayout_19.addWidget(self.trainingFile_lineEdit, 0, 2, 1, 1)
        self.trainingFile_toolButton = QtWidgets.QToolButton(self.frame_3)
        self.trainingFile_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trainingFile_toolButton.setIcon(icon8)
        self.trainingFile_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.trainingFile_toolButton.setObjectName("trainingFile_toolButton")
        self.gridLayout_19.addWidget(self.trainingFile_toolButton, 0, 0, 1, 1)
        self.button_new_input = QtWidgets.QToolButton(self.frame_3)
        self.button_new_input.setStyleSheet("margin: 0px;padding: 0px;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_new_input.setIcon(icon9)
        self.button_new_input.setIconSize(QtCore.QSize(22, 22))
        self.button_new_input.setObjectName("button_new_input")
        self.gridLayout_19.addWidget(self.button_new_input, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_19, 2, 0, 1, 1)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.toolButton_reload = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_reload.setStyleSheet("margin: 0px;padding: 0px;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_reload.setIcon(icon10)
        self.toolButton_reload.setIconSize(QtCore.QSize(22, 22))
        self.toolButton_reload.setObjectName("toolButton_reload")
        self.gridLayout_35.addWidget(self.toolButton_reload, 1, 3, 1, 1)
        self.bandset_toolButton = QtWidgets.QToolButton(self.frame_3)
        self.bandset_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_bandset_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bandset_toolButton.setIcon(icon11)
        self.bandset_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.bandset_toolButton.setObjectName("bandset_toolButton")
        self.gridLayout_35.addWidget(self.bandset_toolButton, 1, 1, 1, 1)
        self.raster_name_combo = QtWidgets.QComboBox(self.frame_3)
        self.raster_name_combo.setObjectName("raster_name_combo")
        self.gridLayout_35.addWidget(self.raster_name_combo, 1, 2, 1, 1)
        self.input_raster_toolButton = QtWidgets.QToolButton(self.frame_3)
        self.input_raster_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.input_raster_toolButton.setIcon(icon8)
        self.input_raster_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.input_raster_toolButton.setObjectName("input_raster_toolButton")
        self.gridLayout_35.addWidget(self.input_raster_toolButton, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_34.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_34.setObjectName("label_34")
        self.gridLayout_35.addWidget(self.label_34, 0, 0, 1, 4)
        self.gridLayout_6.addLayout(self.gridLayout_35, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.main_textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.main_textBrowser.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'DejaVu Sans\';\"><br /></span></p></body></html>")
        self.main_textBrowser.setOpenExternalLinks(True)
        self.main_textBrowser.setObjectName("main_textBrowser")
        self.gridLayout_12.addWidget(self.main_textBrowser, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_35.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_12, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_3, 0, 0, 1, 1)
        self.SCP_toolBox.addItem(self.page_5, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 408, 492))
        self.page_7.setObjectName("page_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.page_7)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_39 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_39.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 0, 0, 1, 1)
        self.signature_list_tableWidget = QtWidgets.QTableWidget(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signature_list_tableWidget.sizePolicy().hasHeightForWidth())
        self.signature_list_tableWidget.setSizePolicy(sizePolicy)
        self.signature_list_tableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.signature_list_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.signature_list_tableWidget.setObjectName("signature_list_tableWidget")
        self.signature_list_tableWidget.setColumnCount(6)
        self.signature_list_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.signature_list_tableWidget.setHorizontalHeaderItem(5, item)
        self.signature_list_tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.signature_list_tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout.addWidget(self.signature_list_tableWidget, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem2, 0, 3, 1, 1)
        self.scatterPlot_toolButton = QtWidgets.QToolButton(self.frame_4)
        self.scatterPlot_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_scatter_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scatterPlot_toolButton.setIcon(icon12)
        self.scatterPlot_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.scatterPlot_toolButton.setObjectName("scatterPlot_toolButton")
        self.gridLayout_28.addWidget(self.scatterPlot_toolButton, 0, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem3, 0, 6, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.import_library_toolButton = QtWidgets.QToolButton(self.frame_4)
        self.import_library_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_import_spectral_library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_library_toolButton.setIcon(icon13)
        self.import_library_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.import_library_toolButton.setObjectName("import_library_toolButton")
        self.gridLayout_2.addWidget(self.import_library_toolButton, 0, 0, 1, 1)
        self.export_signature_list_toolButton = QtWidgets.QToolButton(self.frame_4)
        self.export_signature_list_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_export_spectral_library.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_signature_list_toolButton.setIcon(icon14)
        self.export_signature_list_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.export_signature_list_toolButton.setObjectName("export_signature_list_toolButton")
        self.gridLayout_2.addWidget(self.export_signature_list_toolButton, 0, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_2, 0, 7, 1, 1)
        self.delete_Signature_Button = QtWidgets.QToolButton(self.frame_4)
        self.delete_Signature_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_delete_signature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_Signature_Button.setIcon(icon15)
        self.delete_Signature_Button.setIconSize(QtCore.QSize(22, 22))
        self.delete_Signature_Button.setObjectName("delete_Signature_Button")
        self.gridLayout_28.addWidget(self.delete_Signature_Button, 0, 0, 1, 1)
        self.calculate_signature_toolButton = QtWidgets.QToolButton(self.frame_4)
        self.calculate_signature_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.calculate_signature_toolButton.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_calculate_signature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calculate_signature_toolButton.setIcon(icon16)
        self.calculate_signature_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.calculate_signature_toolButton.setObjectName("calculate_signature_toolButton")
        self.gridLayout_28.addWidget(self.calculate_signature_toolButton, 0, 2, 1, 1)
        self.merge_signature_toolButton = QtWidgets.QToolButton(self.frame_4)
        self.merge_signature_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.merge_signature_toolButton.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_merge_sign_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.merge_signature_toolButton.setIcon(icon17)
        self.merge_signature_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.merge_signature_toolButton.setObjectName("merge_signature_toolButton")
        self.gridLayout_28.addWidget(self.merge_signature_toolButton, 0, 1, 1, 1)
        self.signature_spectral_plot_toolButton = QtWidgets.QToolButton(self.frame_4)
        self.signature_spectral_plot_toolButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_sign_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signature_spectral_plot_toolButton.setIcon(icon18)
        self.signature_spectral_plot_toolButton.setIconSize(QtCore.QSize(22, 22))
        self.signature_spectral_plot_toolButton.setObjectName("signature_spectral_plot_toolButton")
        self.gridLayout_28.addWidget(self.signature_spectral_plot_toolButton, 0, 4, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_28, 0, 1, 1, 5)
        self.gridLayout_21.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.toolBox = QtWidgets.QToolBox(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setObjectName("toolBox")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 371, 265))
        self.page_6.setObjectName("page_6")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.frame = QtWidgets.QFrame(self.page_6)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.display_cursor_checkBox = QtWidgets.QCheckBox(self.frame)
        self.display_cursor_checkBox.setChecked(True)
        self.display_cursor_checkBox.setObjectName("display_cursor_checkBox")
        self.gridLayout_29.addWidget(self.display_cursor_checkBox, 0, 0, 1, 1)
        self.vegetation_index_comboBox = QtWidgets.QComboBox(self.frame)
        self.vegetation_index_comboBox.setObjectName("vegetation_index_comboBox")
        self.vegetation_index_comboBox.addItem("")
        self.vegetation_index_comboBox.addItem("")
        self.vegetation_index_comboBox.addItem("")
        self.gridLayout_29.addWidget(self.vegetation_index_comboBox, 0, 1, 1, 1)
        self.custom_index_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.custom_index_lineEdit.setObjectName("custom_index_lineEdit")
        self.gridLayout_29.addWidget(self.custom_index_lineEdit, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_29, 1, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setVerticalSpacing(4)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.ROI_Class_line = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Class_line.sizePolicy().hasHeightForWidth())
        self.ROI_Class_line.setSizePolicy(sizePolicy)
        self.ROI_Class_line.setMaxLength(80)
        self.ROI_Class_line.setObjectName("ROI_Class_line")
        self.gridLayout_27.addWidget(self.ROI_Class_line, 5, 4, 1, 1)
        self.ROI_Macroclass_ID_spin = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Macroclass_ID_spin.sizePolicy().hasHeightForWidth())
        self.ROI_Macroclass_ID_spin.setSizePolicy(sizePolicy)
        self.ROI_Macroclass_ID_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROI_Macroclass_ID_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROI_Macroclass_ID_spin.setMinimum(0)
        self.ROI_Macroclass_ID_spin.setMaximum(9999)
        self.ROI_Macroclass_ID_spin.setProperty("value", 1)
        self.ROI_Macroclass_ID_spin.setObjectName("ROI_Macroclass_ID_spin")
        self.gridLayout_27.addWidget(self.ROI_Macroclass_ID_spin, 3, 1, 1, 2)
        self.ROI_Macroclass_line = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_Macroclass_line.sizePolicy().hasHeightForWidth())
        self.ROI_Macroclass_line.setSizePolicy(sizePolicy)
        self.ROI_Macroclass_line.setMaxLength(80)
        self.ROI_Macroclass_line.setObjectName("ROI_Macroclass_line")
        self.gridLayout_27.addWidget(self.ROI_Macroclass_line, 3, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMaximumSize(QtCore.QSize(89, 16777215))
        self.label_42.setObjectName("label_42")
        self.gridLayout_27.addWidget(self.label_42, 5, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.gridLayout_27.addWidget(self.label_41, 5, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.gridLayout_27.addWidget(self.label_45, 3, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_44.setObjectName("label_44")
        self.gridLayout_27.addWidget(self.label_44, 3, 0, 1, 1)
        self.ROI_ID_spin = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_ID_spin.sizePolicy().hasHeightForWidth())
        self.ROI_ID_spin.setSizePolicy(sizePolicy)
        self.ROI_ID_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ROI_ID_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROI_ID_spin.setMinimum(0)
        self.ROI_ID_spin.setMaximum(9999)
        self.ROI_ID_spin.setProperty("value", 1)
        self.ROI_ID_spin.setObjectName("ROI_ID_spin")
        self.gridLayout_27.addWidget(self.ROI_ID_spin, 5, 1, 1, 2)
        self.gridLayout_10.addLayout(self.gridLayout_27, 0, 0, 1, 5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.undo_save_Button = QtWidgets.QToolButton(self.frame)
        self.undo_save_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_undo_save_roi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_save_Button.setIcon(icon19)
        self.undo_save_Button.setIconSize(QtCore.QSize(22, 22))
        self.undo_save_Button.setObjectName("undo_save_Button")
        self.horizontalLayout.addWidget(self.undo_save_Button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.signature_checkBox = QtWidgets.QCheckBox(self.frame)
        self.signature_checkBox.setChecked(True)
        self.signature_checkBox.setObjectName("signature_checkBox")
        self.horizontalLayout.addWidget(self.signature_checkBox)
        self.button_Save_ROI = QtWidgets.QToolButton(self.frame)
        self.button_Save_ROI.setStyleSheet("margin: 0px;padding: 0px;")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_save_roi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_Save_ROI.setIcon(icon20)
        self.button_Save_ROI.setIconSize(QtCore.QSize(22, 22))
        self.button_Save_ROI.setObjectName("button_Save_ROI")
        self.horizontalLayout.addWidget(self.button_Save_ROI)
        self.gridLayout_10.addLayout(self.horizontalLayout, 1, 0, 1, 5)
        self.gridLayout_14.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.auto_refresh_ROI_radioButton = QtWidgets.QRadioButton(self.frame)
        self.auto_refresh_ROI_radioButton.setAutoExclusive(False)
        self.auto_refresh_ROI_radioButton.setObjectName("auto_refresh_ROI_radioButton")
        self.gridLayout_34.addWidget(self.auto_refresh_ROI_radioButton, 1, 0, 1, 1)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.rapidROI_band_spinBox = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rapidROI_band_spinBox.sizePolicy().hasHeightForWidth())
        self.rapidROI_band_spinBox.setSizePolicy(sizePolicy)
        self.rapidROI_band_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rapidROI_band_spinBox.setMinimum(1)
        self.rapidROI_band_spinBox.setMaximum(10000)
        self.rapidROI_band_spinBox.setProperty("value", 1)
        self.rapidROI_band_spinBox.setObjectName("rapidROI_band_spinBox")
        self.gridLayout_38.addWidget(self.rapidROI_band_spinBox, 0, 1, 1, 1)
        self.rapid_ROI_checkBox = QtWidgets.QCheckBox(self.frame)
        self.rapid_ROI_checkBox.setObjectName("rapid_ROI_checkBox")
        self.gridLayout_38.addWidget(self.rapid_ROI_checkBox, 0, 0, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout_38, 0, 0, 1, 1)
        self.auto_calculate_ROI_signature_radioButton = QtWidgets.QRadioButton(self.frame)
        self.auto_calculate_ROI_signature_radioButton.setAutoExclusive(False)
        self.auto_calculate_ROI_signature_radioButton.setObjectName("auto_calculate_ROI_signature_radioButton")
        self.gridLayout_34.addWidget(self.auto_calculate_ROI_signature_radioButton, 2, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_34, 2, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_6, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 198, 187))
        self.page_3.setObjectName("page_3")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_5 = QtWidgets.QFrame(self.page_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.label_40 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_40.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_44.addWidget(self.label_40, 0, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_44, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.add_MC_row_Button = QtWidgets.QToolButton(self.frame_5)
        self.add_MC_row_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_MC_row_Button.setIcon(icon21)
        self.add_MC_row_Button.setIconSize(QtCore.QSize(22, 22))
        self.add_MC_row_Button.setObjectName("add_MC_row_Button")
        self.verticalLayout_2.addWidget(self.add_MC_row_Button)
        self.delete_MC_row_Button = QtWidgets.QToolButton(self.frame_5)
        self.delete_MC_row_Button.setStyleSheet("margin: 0px;padding: 0px;")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_MC_row_Button.setIcon(icon22)
        self.delete_MC_row_Button.setIconSize(QtCore.QSize(22, 22))
        self.delete_MC_row_Button.setObjectName("delete_MC_row_Button")
        self.verticalLayout_2.addWidget(self.delete_MC_row_Button)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.gridLayout_23.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.macroclass_color_tableWidget = QtWidgets.QTableWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macroclass_color_tableWidget.sizePolicy().hasHeightForWidth())
        self.macroclass_color_tableWidget.setSizePolicy(sizePolicy)
        self.macroclass_color_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.macroclass_color_tableWidget.setObjectName("macroclass_color_tableWidget")
        self.macroclass_color_tableWidget.setColumnCount(3)
        self.macroclass_color_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.macroclass_color_tableWidget.setHorizontalHeaderItem(2, item)
        self.macroclass_color_tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.macroclass_color_tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.gridLayout_23.addWidget(self.macroclass_color_tableWidget, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem7, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.qml_lineEdit = QtWidgets.QLineEdit(self.frame_5)
        self.qml_lineEdit.setEnabled(False)
        self.qml_lineEdit.setObjectName("qml_lineEdit")
        self.gridLayout_7.addWidget(self.qml_lineEdit, 0, 2, 1, 1)
        self.resetQmlButton = QtWidgets.QToolButton(self.frame_5)
        self.resetQmlButton.setStyleSheet("margin: 0px;padding: 0px;")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetQmlButton.setIcon(icon23)
        self.resetQmlButton.setIconSize(QtCore.QSize(22, 22))
        self.resetQmlButton.setObjectName("resetQmlButton")
        self.gridLayout_7.addWidget(self.resetQmlButton, 0, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 0, 0, 1, 1)
        self.qml_Button = QtWidgets.QToolButton(self.frame_5)
        self.qml_Button.setStyleSheet("margin: 0px;padding: 0px;")
        self.qml_Button.setIcon(icon8)
        self.qml_Button.setIconSize(QtCore.QSize(22, 22))
        self.qml_Button.setObjectName("qml_Button")
        self.gridLayout_7.addWidget(self.qml_Button, 0, 3, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_7, 3, 0, 1, 2)
        self.gridLayout_32.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_5, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_3, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 358, 193))
        self.page.setObjectName("page")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_16.setObjectName("label_16")
        self.gridLayout_33.addWidget(self.label_16, 2, 1, 1, 1)
        self.algorithm_combo = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algorithm_combo.sizePolicy().hasHeightForWidth())
        self.algorithm_combo.setSizePolicy(sizePolicy)
        self.algorithm_combo.setMinimumSize(QtCore.QSize(100, 0))
        self.algorithm_combo.setObjectName("algorithm_combo")
        self.algorithm_combo.addItem("")
        self.algorithm_combo.addItem("")
        self.algorithm_combo.addItem("")
        self.gridLayout_33.addWidget(self.algorithm_combo, 2, 0, 1, 1)
        self.alg_threshold_SpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alg_threshold_SpinBox.sizePolicy().hasHeightForWidth())
        self.alg_threshold_SpinBox.setSizePolicy(sizePolicy)
        self.alg_threshold_SpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.alg_threshold_SpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.alg_threshold_SpinBox.setDecimals(4)
        self.alg_threshold_SpinBox.setMaximum(10000.0)
        self.alg_threshold_SpinBox.setObjectName("alg_threshold_SpinBox")
        self.gridLayout_33.addWidget(self.alg_threshold_SpinBox, 2, 2, 1, 1)
        self.algorithm_threshold_button = QtWidgets.QToolButton(self.frame_2)
        self.algorithm_threshold_button.setStyleSheet("margin: 0px;padding: 0px;")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_threshold_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.algorithm_threshold_button.setIcon(icon24)
        self.algorithm_threshold_button.setIconSize(QtCore.QSize(22, 22))
        self.algorithm_threshold_button.setObjectName("algorithm_threshold_button")
        self.gridLayout_33.addWidget(self.algorithm_threshold_button, 2, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.macroclass_checkBox = QtWidgets.QCheckBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macroclass_checkBox.sizePolicy().hasHeightForWidth())
        self.macroclass_checkBox.setSizePolicy(sizePolicy)
        self.macroclass_checkBox.setObjectName("macroclass_checkBox")
        self.horizontalLayout_3.addWidget(self.macroclass_checkBox)
        self.class_checkBox = QtWidgets.QCheckBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class_checkBox.sizePolicy().hasHeightForWidth())
        self.class_checkBox.setSizePolicy(sizePolicy)
        self.class_checkBox.setObjectName("class_checkBox")
        self.horizontalLayout_3.addWidget(self.class_checkBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.algorithm_weight_button = QtWidgets.QToolButton(self.frame_2)
        self.algorithm_weight_button.setStyleSheet("margin: 0px;padding: 0px;")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_weight_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.algorithm_weight_button.setIcon(icon25)
        self.algorithm_weight_button.setIconSize(QtCore.QSize(22, 22))
        self.algorithm_weight_button.setObjectName("algorithm_weight_button")
        self.horizontalLayout_3.addWidget(self.algorithm_weight_button)
        self.gridLayout_33.addLayout(self.horizontalLayout_3, 0, 0, 1, 4)
        self.label_43 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_43.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_33.addWidget(self.label_43, 1, 0, 1, 4)
        self.gridLayout_5.addLayout(self.gridLayout_33, 0, 0, 1, 2)
        self.gridLayout_43 = QtWidgets.QGridLayout()
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.gridLayout_43.addWidget(self.label_21, 1, 0, 1, 1)
        self.LC_signature_checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.LC_signature_checkBox.setObjectName("LC_signature_checkBox")
        self.gridLayout_43.addWidget(self.LC_signature_checkBox, 1, 1, 1, 1)
        self.LCS_class_algorithm_checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.LCS_class_algorithm_checkBox.setObjectName("LCS_class_algorithm_checkBox")
        self.gridLayout_43.addWidget(self.LCS_class_algorithm_checkBox, 1, 2, 1, 1)
        self.LCS_leave_unclassified_checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.LCS_leave_unclassified_checkBox.setObjectName("LCS_leave_unclassified_checkBox")
        self.gridLayout_43.addWidget(self.LCS_leave_unclassified_checkBox, 1, 3, 1, 1)
        self.LC_signature_button = QtWidgets.QToolButton(self.frame_2)
        self.LC_signature_button.setStyleSheet("margin: 0px;padding: 0px;")
        self.LC_signature_button.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_LCS_threshold_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LC_signature_button.setIcon(icon26)
        self.LC_signature_button.setIconSize(QtCore.QSize(22, 22))
        self.LC_signature_button.setObjectName("LC_signature_button")
        self.gridLayout_43.addWidget(self.LC_signature_button, 1, 4, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #535353, stop:1 #a6a6a6); color : white")
        self.label_46.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_43.addWidget(self.label_46, 0, 0, 1, 5)
        self.gridLayout_5.addLayout(self.gridLayout_43, 1, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_39.addWidget(self.frame_2, 0, 1, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 298, 188))
        self.page_4.setObjectName("page_4")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.frame_7 = QtWidgets.QFrame(self.page_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSpacing(4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.mask_checkBox = QtWidgets.QCheckBox(self.frame_7)
        self.mask_checkBox.setObjectName("mask_checkBox")
        self.gridLayout_13.addWidget(self.mask_checkBox, 0, 0, 1, 1)
        self.mask_lineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.mask_lineEdit.setEnabled(False)
        self.mask_lineEdit.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.mask_lineEdit.setText("")
        self.mask_lineEdit.setObjectName("mask_lineEdit")
        self.gridLayout_13.addWidget(self.mask_lineEdit, 0, 2, 1, 1)
        self.resetMaskButton = QtWidgets.QToolButton(self.frame_7)
        self.resetMaskButton.setStyleSheet("margin: 0px;padding: 0px;")
        self.resetMaskButton.setIcon(icon23)
        self.resetMaskButton.setIconSize(QtCore.QSize(22, 22))
        self.resetMaskButton.setObjectName("resetMaskButton")
        self.gridLayout_13.addWidget(self.resetMaskButton, 0, 3, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_13, 2, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vector_output_checkBox = QtWidgets.QCheckBox(self.frame_7)
        self.vector_output_checkBox.setObjectName("vector_output_checkBox")
        self.horizontalLayout_2.addWidget(self.vector_output_checkBox)
        self.report_checkBox = QtWidgets.QCheckBox(self.frame_7)
        self.report_checkBox.setObjectName("report_checkBox")
        self.horizontalLayout_2.addWidget(self.report_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.alg_files_checkBox = QtWidgets.QCheckBox(self.frame_7)
        self.alg_files_checkBox.setObjectName("alg_files_checkBox")
        self.horizontalLayout_4.addWidget(self.alg_files_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.button_classification = QtWidgets.QToolButton(self.frame_7)
        self.button_classification.setStyleSheet("margin: 0px;padding: 0px;")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/plugins/semiautomaticclassificationplugin/icons/semiautomaticclassificationplugin_run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_classification.setIcon(icon27)
        self.button_classification.setIconSize(QtCore.QSize(34, 34))
        self.button_classification.setObjectName("button_classification")
        self.gridLayout_41.addWidget(self.button_classification, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_41.addItem(spacerItem10, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_41)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.gridLayout_42.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.frame_7, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_4, "")
        self.gridLayout_17.addWidget(self.toolBox, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_17, 1, 0, 1, 1)
        self.SCP_toolBox.addItem(self.page_7, "")
        self.gridLayout_46.addWidget(self.SCP_toolBox, 0, 0, 1, 1)
        DockClass.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockClass)
        self.SCP_toolBox.setCurrentIndex(0)
        self.SCP_toolBox.layout().setSpacing(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(DockClass)

    def retranslateUi(self, DockClass):
        _translate = QtCore.QCoreApplication.translate
        DockClass.setWindowTitle(_translate("DockClass", "SCP Dock"))
        self.bandcalc_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Band calc</span></p></body></html>"))
        self.ROItools_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Tools</span></p></body></html>"))
        self.preprocessing_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Preprocessing</p></body></html>"))
        self.settings_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Settings</span></p></body></html>"))
        self.postprocessing_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>Postprocessing</p></body></html>"))
        self.userguide_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p>User manual</p></body></html>"))
        self.help_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Online help</span></p></body></html>"))
        self.download_images_toolButton_2.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Download images</span></p></body></html>"))
        self.label_33.setText(_translate("DockClass", " Training input"))
        self.trainingFile_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Input file path</p></body></html>"))
        self.trainingFile_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Open a training input</span></p></body></html>"))
        self.button_new_input.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Create a new training input</span></p></body></html>"))
        self.toolButton_reload.setToolTip(_translate("DockClass", "<html><head/><body><p >Refresh list</p></body></html>"))
        self.toolButton_reload.setText(_translate("DockClass", "Plot"))
        self.bandset_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Band set</span></p></body></html>"))
        self.raster_name_combo.setToolTip(_translate("DockClass", "<html><head/><body><p>Select an image</p></body></html>"))
        self.input_raster_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Open a file</p></body></html>"))
        self.label_34.setText(_translate("DockClass", " Input image"))
        self.label_35.setText(_translate("DockClass", " SCP news"))
        self.SCP_toolBox.setItemText(self.SCP_toolBox.indexOf(self.page_5), _translate("DockClass", "SCP input"))
        self.label_39.setText(_translate("DockClass", " ROI Signature list"))
        self.signature_list_tableWidget.setSortingEnabled(True)
        item = self.signature_list_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DockClass", "S"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DockClass", "Type"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DockClass", "MC ID"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DockClass", "C ID"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DockClass", "C Info"))
        item = self.signature_list_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DockClass", "Color"))
        self.scatterPlot_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Add highlighted items to scatter plot</p></body></html>"))
        self.scatterPlot_toolButton.setText(_translate("DockClass", "..."))
        self.import_library_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Import spectral signatures </p></body></html>"))
        self.import_library_toolButton.setText(_translate("DockClass", "Import library"))
        self.export_signature_list_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Export highlighted spectral signatures</p></body></html>\n"
""))
        self.export_signature_list_toolButton.setText(_translate("DockClass", "Import library"))
        self.delete_Signature_Button.setToolTip(_translate("DockClass", "<html><head/><body><p>Delete highlighted items</p></body></html>"))
        self.delete_Signature_Button.setText(_translate("DockClass", "..."))
        self.calculate_signature_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate signatures for highlighted items</p></body></html>"))
        self.merge_signature_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Merge highlighted spectral signatures obtaining the average signature</p></body></html>"))
        self.signature_spectral_plot_toolButton.setToolTip(_translate("DockClass", "<html><head/><body><p >Add highlighted signatures to spectral signature plot</p></body></html>"))
        self.signature_spectral_plot_toolButton.setText(_translate("DockClass", "Plot"))
        self.display_cursor_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Display a vegetation index value with the cursor</p></body></html>"))
        self.display_cursor_checkBox.setText(_translate("DockClass", "Display"))
        self.vegetation_index_comboBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Select a vegetation index</p></body></html>"))
        self.vegetation_index_comboBox.setItemText(0, _translate("DockClass", "NDVI"))
        self.vegetation_index_comboBox.setItemText(1, _translate("DockClass", "EVI"))
        self.vegetation_index_comboBox.setItemText(2, _translate("DockClass", "Custom"))
        self.custom_index_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Custom expression (e.g. bandset#b4 / bandset#b3 )</p></body></html>"))
        self.ROI_Class_line.setToolTip(_translate("DockClass", "<html><head/><body><p>The class name of the ROI signature</p></body></html>"))
        self.ROI_Class_line.setText(_translate("DockClass", "C 1"))
        self.ROI_Macroclass_ID_spin.setToolTip(_translate("DockClass", "<html><head/><body><p>The macroclass ID of the ROI signature</p></body></html>"))
        self.ROI_Macroclass_line.setToolTip(_translate("DockClass", "<html><head/><body><p>The macroclass name of the ROI signature</p></body></html>"))
        self.ROI_Macroclass_line.setText(_translate("DockClass", "MC 1"))
        self.label_42.setText(_translate("DockClass", "C ID"))
        self.label_41.setText(_translate("DockClass", "C Info"))
        self.label_45.setText(_translate("DockClass", "MC Info"))
        self.label_44.setText(_translate("DockClass", "MC ID"))
        self.ROI_ID_spin.setToolTip(_translate("DockClass", "<html><head/><body><p>The class ID of the ROI signature</p></body></html>"))
        self.undo_save_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Undo ROI save</p></body></html>"))
        self.undo_save_Button.setText(_translate("DockClass", "Import library"))
        self.signature_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Add ROI spectral signature to signature list</p></body></html>"))
        self.signature_checkBox.setText(_translate("DockClass", "Calculate sig."))
        self.button_Save_ROI.setToolTip(_translate("DockClass", "<html><head/><body><p >Save temporary ROI to training input</p></body></html>"))
        self.button_Save_ROI.setText(_translate("DockClass", "Import library"))
        self.auto_refresh_ROI_radioButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically refresh the temporary ROI, as the parameters change</p></body></html>"))
        self.auto_refresh_ROI_radioButton.setText(_translate("DockClass", "Automatic refresh ROI"))
        self.rapidROI_band_spinBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Band number</p></body></html>"))
        self.rapid_ROI_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate temporary ROI only on one band</p></body></html>"))
        self.rapid_ROI_checkBox.setText(_translate("DockClass", "Rapid ROI band"))
        self.auto_calculate_ROI_signature_radioButton.setToolTip(_translate("DockClass", "<html><head/><body><p>Automatically calculate signature plot of temporary ROI</p></body></html>"))
        self.auto_calculate_ROI_signature_radioButton.setText(_translate("DockClass", "Automatic  plot"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("DockClass", "ROI creation"))
        self.label_40.setText(_translate("DockClass", "Classification style"))
        self.add_MC_row_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Add row</p></body></html>"))
        self.add_MC_row_Button.setText(_translate("DockClass", "Plot"))
        self.delete_MC_row_Button.setToolTip(_translate("DockClass", "<html><head/><body><p >Delete row</p></body></html>"))
        self.delete_MC_row_Button.setText(_translate("DockClass", "Plot"))
        self.macroclass_color_tableWidget.setSortingEnabled(True)
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DockClass", "MC ID"))
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DockClass", "MC Info"))
        item = self.macroclass_color_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DockClass", "Color"))
        self.qml_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Qml file path</p></body></html>"))
        self.resetQmlButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Reset</span></p></body></html>"))
        self.resetQmlButton.setText(_translate("DockClass", "Import library"))
        self.label_19.setText(_translate("DockClass", "Load qml"))
        self.qml_Button.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Select qml style</span></p></body></html>"))
        self.qml_Button.setText(_translate("DockClass", "Import library"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("DockClass", " Macroclasses"))
        self.label_16.setText(_translate("DockClass", "Threshold"))
        self.algorithm_combo.setToolTip(_translate("DockClass", "<html><head/><body><p>Select a classification algorithm</p></body></html>"))
        self.algorithm_combo.setItemText(0, _translate("DockClass", "Minimum Distance"))
        self.algorithm_combo.setItemText(1, _translate("DockClass", "Maximum Likelihood"))
        self.algorithm_combo.setItemText(2, _translate("DockClass", "Spectral Angle Mapping"))
        self.alg_threshold_SpinBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Set a classification threshold for all signatures</p></body></html>"))
        self.algorithm_threshold_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab Signature threshold</p></body></html>"))
        self.algorithm_threshold_button.setText(_translate("DockClass", "W"))
        self.label_20.setText(_translate("DockClass", "Use"))
        self.macroclass_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Use the ID of macroclasses for the classification</p></body></html>"))
        self.macroclass_checkBox.setText(_translate("DockClass", "MC ID"))
        self.class_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Use the ID of classes for the classification</p></body></html>"))
        self.class_checkBox.setText(_translate("DockClass", "C ID"))
        self.algorithm_weight_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab Algorithm band weight</p></body></html>"))
        self.algorithm_weight_button.setText(_translate("DockClass", "W"))
        self.label_43.setText(_translate("DockClass", " Algorithm"))
        self.label_21.setText(_translate("DockClass", "Use"))
        self.LC_signature_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the Land Cover Signature Classification is used</p></body></html>"))
        self.LC_signature_checkBox.setText(_translate("DockClass", "LCS"))
        self.LCS_class_algorithm_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the selected Algorithm is used for unclassified pixels of the Land Cover Signature Classification</p></body></html>"))
        self.LCS_class_algorithm_checkBox.setText(_translate("DockClass", "Algorithm"))
        self.LCS_leave_unclassified_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If checked, the selected Algorithm is used only for class overlapping pixels of the Land Cover Signature Classification</p></body></html>"))
        self.LCS_leave_unclassified_checkBox.setText(_translate("DockClass", "only overlap"))
        self.LC_signature_button.setToolTip(_translate("DockClass", "<html><head/><body><p>Open tab LCS threshold</p></body></html>"))
        self.label_46.setText(_translate("DockClass", " Land Cover Signature Classification"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("DockClass", " Classification algorithm"))
        self.mask_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Select an optional mask vector</p></body></html>"))
        self.mask_checkBox.setText(_translate("DockClass", "Apply mask"))
        self.mask_lineEdit.setToolTip(_translate("DockClass", "<html><head/><body><p>Path of the optional mask shapefile</p></body></html>"))
        self.resetMaskButton.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Reset</span></p></body></html>"))
        self.resetMaskButton.setText(_translate("DockClass", "Import library"))
        self.vector_output_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Create a classification shapefile after the classification process</p></body></html>"))
        self.vector_output_checkBox.setText(_translate("DockClass", "Create vector"))
        self.report_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>Calculate a classification report</p></body></html>"))
        self.report_checkBox.setText(_translate("DockClass", "Classification report"))
        self.alg_files_checkBox.setToolTip(_translate("DockClass", "<html><head/><body><p>If enabled, the rasters calculated by the classification algorithm (one per signature) are saved along with the classification</p></body></html>"))
        self.alg_files_checkBox.setText(_translate("DockClass", "Save algorithm files"))
        self.button_classification.setToolTip(_translate("DockClass", "<html><head/><body><p><span >Run</span></p></body></html>"))
        self.button_classification.setText(_translate("DockClass", "Import library"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("DockClass", " Classification output"))
        self.SCP_toolBox.setItemText(self.SCP_toolBox.indexOf(self.page_7), _translate("DockClass", "Classification dock"))

from .resources_rc import *